version: '2'
services:
  db-finances:
    image: postgres
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_DB: finances
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: