version: '3.8'
services:
  pet_finances:
    image: "registry/pet_finances-prod:latest"
    container_name: "pet_finances"
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure